#!/bin/bash

# Installs node if it isn't already installed
#
# Don't steamroll over a previously installed node version
# TODO provide a local version of node?

VER="7.2.0"
ARCH="x86"
if [ `arch | grep 64` ]
then
  ARCH="x64"
fi

# TODO test version
if [ ! -f /usr/local/bin/node ]
then
  pushd /tmp
  wget -c "http://nodejs.org/dist/v${VER}/node-v${VER}-linux-${ARCH}.tar.gz"
  rm -rf /tmp/node-v${VER}-linux-${ARCH}
  tar xf node-v${VER}-linux-${ARCH}.tar.gz -C /tmp/
  cp -a /tmp/node-v${VER}-linux-${ARCH}/* /usr/local/
fi

# Create pm-agent user with no password
useradd pm-agent -s /bin/bash -p '*' || true
