FROM alpine:3.18.2

RUN apk --no-cache add nodejs npm bash curl git docker-cli

WORKDIR /twiddlebug
ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug/shared
ADD ./shared/package.json ./package.json
ADD ./shared/package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug
ADD ./ ./
RUN rm -rf ./libs
RUN rm -rf ./kaholo-agent.conf

CMD npm start
