#!/bin/sh

set -e
cd /lib/systemd/system
sudo systemctl daemon-reload

cd /var/lib/kaholo/kaholo-agent
npm install --production

if [ ! -f /etc/kaholo-agent/kaholo-agent.conf ]; then
    cp /var/lib/kaholo/kaholo-agent/kaholo-agent.conf.example /etc/kaholo-agent/kaholo-agent.conf
fi